### PR TITLE
Encode arrays correctly in query params.

### PR DESCRIPTION
**Pull request by noelzubin**
Closes https://github.com/loadimpact/k6/issues/1713

### CODE REVIEW

**Review by na-- — COMMENTED** [review]
Thanks for making this PR. I guess picking to reuse the same key for all slice values (instead of `key[]` or `key.<N>` or any other convention) is better than the current behavior (https://github.com/loadimpact/k6/issues/1713, https://github.com/loadimpact/k6/issues/878)...

Can you please add some tests in your PR? And also you probably don't need reflection, you should be able to get by with a simple [type assertion](https://tour.golang.org/methods/15) that `v` is `[]interface{}`?

**Comment by noelzubin** [comment]
@na-- I dont think go allows type assertion on []interface{}, Although it allows type assertions on []string though.

**Comment by na--** [comment]
Ah, yeah, fair enough... :man_facepalming: Though the rest of my request still stands - please add some tests, and also you probably don't need to check for `reflect.Array` in the `switch`, which should take care of the lint error as well.

**Review by imiric — CHANGES_REQUESTED** [review]
@noelzubin Thanks for the PR. Are you available to finish it? We'd like to have this merged for v0.33.0. I think it would just need a test and maybe disabling the `exhaustive` linter if we can't avoid the reflection.

If we don't hear from you by sometime next week or if you're not available, that's OK too, and we can proceed to do the leftover changes.

**Comment by imiric** [comment]
Fixed in #2060.

Thanks for your contribution @noelzubin! We'll make sure to thank you in the release notes :)

**Pull request closed without merging**
