### PR TITLE
Update other dependencies

### PR DESCRIPTION
**Pull request by MStoykov**
This updates the majority of the k6 dependencies that we intended to update from #1933.

The biggest size increases are from yaml.v3 addition, compression algorithms, and testify additions.

### CODE REVIEW

**Comment by MStoykov** [comment]
The only remaining dependencies that should be updated at all from https://github.com/k6io/k6/issues/1933 are:
- `github.com/DataDog/datadog-go` there were a lot of changes including new dependencies for support of windows pipes and some aggregation code. Given that it still doesn't support tcp and we might want to add some support for the aggregation I decided I should look at it more closely and open an issue to discuss what we should do.
- `github.com/fatih/color`, `github.com/mattn/go-colorable` and `github.com/mattn/go-isatty` - there are a lot of changes here including a lot of fixes for windows (supposedly). I did test it under Linux somewhat, but decided that given the amount of changes a lot more testing under windows will be needed and decided that would mean it should be in a separate PR
- `github.com/spf13/cobra` and `github.com/spf13/pflag` - again a lot more changes including more support for context and some windows related changes. So it is actually a combination of the two above - I want to look at the changes in more detail and it likely will require more testing under windows. Also did update color libraries somewhat which means that it should probably happen after we update those ;)

There were no updates for:
- `github.com/nu7hatch/gouuid` 
- `github.com/mccutchen/go-httpbin`

**Review by na-- — CHANGES_REQUESTED** [review]
This PR adds `gopkg.in/yaml.v3`, while keeping `gopkg.in/yaml.v2`. I think we can drop the latter with a minor change in k6:
```
$ go mod why 'gopkg.in/yaml.v3'
# gopkg.in/yaml.v3
github.com/loadimpact/k6/lib/testutils/httpmultibin
github.com/stretchr/testify/assert
gopkg.in/yaml.v3
$ go mod why 'gopkg.in/yaml.v2'
# gopkg.in/yaml.v2
github.com/loadimpact/k6/ui
gopkg.in/yaml.v2
```

**Comment by MStoykov** [comment]
Unfortunately - not @na-- , as it's also used in `gin` and another `yaml` library which used by `helm` of which we use `strvals`

Also even if we could I prefer to do it in a separate PR, where I will drop the direct uses by k6

**Review by na-- — APPROVED** [review]
https://github.com/golang/go/issues/41305 ... :disappointed:

**Review by imiric — APPROVED** [review]
:crossed_fingers: A lot of new LOCs, but it seems unavoidable.

Nice job reviewing each update and detailing it in separate commits! :clap:

**Pull request merged**
