### PR TITLE
quick fix for #994

### PR DESCRIPTION
**Pull request by MStoykov**

### CODE REVIEW

**Comment by MStoykov** [comment]
The more correct way to do this will be to wrap the [goja.Exception](https://pkg.go.dev/github.com/dop251/goja?utm_source=godoc#Exception) in some lib.Exception interface that we check for both at this place and at the https://github.com/loadimpact/k6/blob/ef717e1af2a92d35d39a3d815a69b6ab6b8c65e1/lib/executor/helpers.go#L99-L103 ? Or maybe I should just move this wrapping I do in this PR in the js/runner and wrap all Exceptions like that ?

**Comment by imiric** [comment]
I'm not sure what the proper fix for this should be, but the current change shows the same error with the example in #994 as reported there, and as shown on `master`. Isn't it the idea that it should show a full stack trace instead?

**Comment by MStoykov** [comment]
> I'm not sure what the proper fix for this should be, but the current change shows the same error with the example in #994 as reported there, and as shown on master. Isn't it the idea that it should show a full stack trace instead?

I was fixing it for cases as https://community.k6.io/t/goerror-invalid-url-value-nil/1491/8 which seemed like it will work, but apparently the code I changed in 782d775 wraps the cases coming from setup/teardown ;(

**Comment by MStoykov** [comment]
superseded by #1971

**Pull request closed without merging**
