### PR TITLE
Fix a mistake in the v0.32.0 release notes

### PR DESCRIPTION
**Pull request by na--**
Not sure how we missed this :sweat_smile: :man_facepalming:

### CODE REVIEW

**Comment by na--** [comment]
We should just get rid of Codecov, with PRs like this it's obvious how completely wrong it is :confused:

**Review by MStoykov — APPROVED** [review]

**Comment by MStoykov** [comment]
> We should just get rid of Codecov, with PRs like this it's obvious how completely wrong it is confused

I can't currently open to see which 1 line is now not being covered, but it is very possible that between some runs we don't run all lines. I am still fine with dropping codecov, but if we are dropping it I prefer to replace it in not this release cycle as 1 release  cycle of mostly CI changes in enough for me :P

**Comment by na--** [comment]
Hmm seems codecodev has updated the comment since, it used to be way more wrong. Click on the `edited` field in the top, see the initial version and how completely wrong it was.

**Comment by MStoykov** [comment]
It seems like it updated with the `windows` specific tests as well ... at least from that edit

**Pull request merged**
